[package]
name = "canadensis_serial"
version = "0.2.2"
edition = "2018"
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
keywords = ["uavcan", "embedded", "cyphal"]
description = "A Cyphal implementation: Cyphal/Serial transport"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = "0.6.0"
heapless = "0.7.7"
crc-any = "2.4.0"
fallible_collections = "0.4"
log = "0.4.14"
hash32 = "0.2.1"
hash32-derive = "0.1.1"

[dependencies.canadensis_core]
version = "0.2.0"
path = "../canadensis_core"
[dependencies.canadensis_header]
version = "0.1.0"
path = "../canadensis_header"

[dev-dependencies]
simplelog = "0.10.2"
