[package]
name = "canadensis_core"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1.0 implementation: Common definitions"

[dependencies]
hash32 = "0.2.1"
hash32-derive = "0.1.0"
fallible_collections = "0.4.0"
heapless = "0.7.7"
log = "0.4.14"
nb = "1.0.0"
